//! widespread_wallet — the Widespread LEZ wallet as a LogosCore module.
//!
//! Hosts `wsp_lez_core::Worker` behind the generated module-impl C ABI. The
//! `execute` method is the shared worker contract (identical wire format to
//! `wsp-lezd` native messaging and the `wsp-lez` CLI); the SDK methods are a
//! typed convenience surface for Logos dApps that routes through the same
//! worker, with the approval gate applied in the signing path.

// Generated by logos-lidl-gen — lints are suppressed at the module boundary
// rather than editing generated output (regenerations stay clean).
#[allow(clippy::all)]
mod provider_gen {
    include!("provider_gen.rs");
}
#[allow(unused_imports)]
pub use provider_gen::*;

use wsp_lez_core::{Op, Worker};

/// The module instance: one worker session per loaded module instance.
struct WalletImpl {
    worker: Worker,
}

impl Default for WalletImpl {
    fn default() -> Self {
        Self {
            worker: Worker::new().expect("tokio runtime for wallet worker"),
        }
    }
}

fn run(worker: &mut Worker, op: Op) -> Vec<u8> {
    match worker.execute(op) {
        Ok(out) => serde_json::to_vec(&out).unwrap_or_default(),
        Err(e) => serde_json::to_vec(&serde_json::json!({
            "type": "error",
            "message": format!("{e:#}"),
        }))
        .unwrap_or_default(),
    }
}

impl WidespreadWalletModule for WalletImpl {
    fn execute(&mut self, op: Vec<u8>) -> Vec<u8> {
        match serde_json::from_slice::<Op>(&op) {
            Ok(parsed) => run(&mut self.worker, parsed),
            Err(e) => serde_json::to_vec(&serde_json::json!({
                "type": "error",
                "message": format!("bad op envelope: {e}"),
            }))
            .unwrap_or_default(),
        }
    }

    /// dApp connection request. `dapp_info` is a JSON object:
    /// `{name, origin?, requested_scopes?: [...]}`. Until the approval gate
    /// resolves the request this returns a `needs_approval` envelope and the
    /// `approvalRequested` event carries the request for the UI to act on.
    fn connect(&mut self, dapp_info: Vec<u8>) -> Vec<u8> {
        let request_id = next_request_id();
        emit_approval_requested(request_id, &dapp_info);
        serde_json::to_vec(&serde_json::json!({
            "type": "needs_approval",
            "request_id": request_id,
        }))
        .unwrap_or_default()
    }

    fn get_accounts(&mut self) -> Vec<u8> {
        run(&mut self.worker, Op::ListAccounts)
    }

    fn get_balance(&mut self, account: String) -> Vec<u8> {
        run(&mut self.worker, Op::Balance { account })
    }

    /// Transaction proposal. The request is gated on user approval before
    /// anything is signed or submitted: this emits `approvalRequested` with
    /// the call's human-readable summary and returns `needs_approval`; the
    /// actual `Transfer`/`ProgramCall` op is issued by the approval path once
    /// the user confirms (see docs/PROVIDER-SDK.md for the flow contract).
    fn propose_transaction(&mut self, request: Vec<u8>) -> Vec<u8> {
        let request_id = next_request_id();
        emit_approval_requested(request_id, &request);
        serde_json::to_vec(&serde_json::json!({
            "type": "needs_approval",
            "request_id": request_id,
        }))
        .unwrap_or_default()
    }

    fn get_status(&mut self) -> Vec<u8> {
        run(&mut self.worker, Op::Status)
    }
}

static REQUEST_COUNTER: std::sync::atomic::AtomicI64 = std::sync::atomic::AtomicI64::new(1);

fn next_request_id() -> i64 {
    REQUEST_COUNTER.fetch_add(1, std::sync::atomic::Ordering::Relaxed)
}

#[no_mangle]
pub extern "Rust" fn logos_module_install() {
    install::<WalletImpl>();
}

#[cfg(test)]
mod tests {
    use super::*;

    fn op_bytes(op: Op) -> Vec<u8> {
        serde_json::to_vec(&op).unwrap_or_default()
    }

    #[test]
    fn ping_through_execute() {
        let mut m = WalletImpl::default();
        let out = m.execute(op_bytes(Op::Ping));
        let parsed: serde_json::Value = serde_json::from_slice(&out).unwrap();
        assert_eq!(parsed["type"], "pong");
    }
}
