#!/usr/bin/env bash
# Build the wallet-ui web bundle and generate the QML Resources.js that
# embeds it (bundled — the WebView can't XHR sibling files).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WEB="$ROOT/web/wallet"
OUT_QML_RES="$ROOT/modules/widespread_wallet_ui/src/qml/Resources.js"

cd "$WEB"
if [[ ! -d node_modules ]]; then
  npm install --no-audit --no-fund
fi
npm run build

mkdir -p "$(dirname "$OUT_QML_RES")"

python3 - "$WEB" "$OUT_QML_RES" <<'PY'
import json, sys, pathlib

web = pathlib.Path(sys.argv[1])
out = pathlib.Path(sys.argv[2])
bundle = (web / "dist/bundle.js").read_text()
bridge = (web / "src/bridge.js").read_text()
html = (web / "index.html").read_text().replace(
    '<script type="module" src="./bundle.js"></script>',
    '<script type="module">\n' + bundle + '\n</script>',
)
res = (
    "// Generated by scripts/build-ui.sh — do not edit.\n"
    ".pragma library\n\n"
    "var bridgeScript = " + json.dumps(bridge) + ";\n\n"
    "var walletHtml = " + json.dumps(html) + ";\n"
)
out.write_text(res)
print(f"wrote {out} ({len(res)} bytes)")
PY
